// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SellerData;

namespace SellerData.Migrations
{
    [DbContext(typeof(SellerDbContext))]
    [Migration("20181120192234_ne")]
    partial class ne
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProductData.Models.ImageSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ItemId");

                    b.Property<string>("Original")
                        .IsRequired();

                    b.Property<string>("Thumbnail");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ImageSource");
                });

            modelBuilder.Entity("ProductData.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Approved");

                    b.Property<int?>("CartId");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<double>("Discount");

                    b.Property<int>("InStock");

                    b.Property<int?>("ItemRatingId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<double>("Price");

                    b.Property<string>("Properties")
                        .IsRequired();

                    b.Property<DateTime>("Updated");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ItemRatingId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("ProductData.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count");

                    b.Property<double>("Value");

                    b.HasKey("Id");

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("ProductData.ProductModels.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Updated");

                    b.HasKey("Id");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("ProductData.ProductModels.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("City");
                });

            modelBuilder.Entity("ProductData.ProductModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<int?>("CurrentCartId");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("PostalCode")
                        .IsRequired();

                    b.Property<int?>("UserCityId");

                    b.HasKey("Id");

                    b.HasIndex("CurrentCartId");

                    b.HasIndex("UserCityId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("SellerData.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<DateTime>("Time");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("SellerData.SellerModels.Item", b =>
                {
                    b.Property<int>("Id");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int?>("OrdersId");

                    b.Property<int?>("SellerId");

                    b.HasKey("Id");

                    b.HasIndex("OrdersId");

                    b.HasIndex("SellerId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SellerData.SellerModels.Orders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<double>("Price");

                    b.Property<int>("Status");

                    b.Property<int?>("userId");

                    b.HasKey("Id");

                    b.HasIndex("userId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SellerData.SellerModels.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ReviewCount");

                    b.Property<double>("TotalValue");

                    b.HasKey("Id");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("SellerData.SellerModels.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<bool>("Approved");

                    b.Property<string>("Description");

                    b.Property<bool>("Gender");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("PostalCode")
                        .IsRequired();

                    b.Property<int?>("SellerRatingId");

                    b.Property<double>("SuccessProcent");

                    b.HasKey("Id");

                    b.HasIndex("SellerRatingId");

                    b.ToTable("Sellers");
                });

            modelBuilder.Entity("SellerData.SellerModels.Shipping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("ExpectedTime");

                    b.Property<int>("Method");

                    b.Property<bool>("Notifications");

                    b.Property<int>("OrderInfoId");

                    b.HasKey("Id");

                    b.HasIndex("OrderInfoId");

                    b.ToTable("Shippings");
                });

            modelBuilder.Entity("ProductData.Models.ImageSource", b =>
                {
                    b.HasOne("ProductData.Models.Item")
                        .WithMany("ItemImages")
                        .HasForeignKey("ItemId");
                });

            modelBuilder.Entity("ProductData.Models.Item", b =>
                {
                    b.HasOne("ProductData.ProductModels.Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId");

                    b.HasOne("ProductData.Models.Rating", "ItemRating")
                        .WithMany()
                        .HasForeignKey("ItemRatingId");
                });

            modelBuilder.Entity("ProductData.ProductModels.User", b =>
                {
                    b.HasOne("ProductData.ProductModels.Cart", "CurrentCart")
                        .WithMany()
                        .HasForeignKey("CurrentCartId");

                    b.HasOne("ProductData.ProductModels.City", "UserCity")
                        .WithMany()
                        .HasForeignKey("UserCityId");
                });

            modelBuilder.Entity("SellerData.SellerModels.Item", b =>
                {
                    b.HasOne("SellerData.SellerModels.Orders")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrdersId");

                    b.HasOne("SellerData.SellerModels.Seller")
                        .WithMany("SellerItems")
                        .HasForeignKey("SellerId");
                });

            modelBuilder.Entity("SellerData.SellerModels.Orders", b =>
                {
                    b.HasOne("ProductData.ProductModels.User", "user")
                        .WithMany()
                        .HasForeignKey("userId");
                });

            modelBuilder.Entity("SellerData.SellerModels.Seller", b =>
                {
                    b.HasOne("SellerData.SellerModels.Rating", "SellerRating")
                        .WithMany()
                        .HasForeignKey("SellerRatingId");
                });

            modelBuilder.Entity("SellerData.SellerModels.Shipping", b =>
                {
                    b.HasOne("SellerData.SellerModels.Orders", "OrderInfo")
                        .WithMany()
                        .HasForeignKey("OrderInfoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
